const clubs = [
  {
    name: 'ILS',
    time: '토4',
    kind: '스포츠',
    keyword: '축구',
    sentence:
      '축구를 통해 공부 스트레스를 싹 날려버리고, 선후배+학우관계의 결속력을 다집니다.',
    big: false,
    nickname: '일스',
  },
  {
    name: 'LOD',
    time: '목8',
    kind: '퍼포먼스',
    keyword: '댄스',
    sentence: '현대청운고 유일무이 댄스동아리',
    big: false,
    nickname: '엘오디',
  },
  {
    name: 'MEME',
    time: '목7',
    kind: '메디컬',
    keyword: '의학',
    sentence: '의사를 꿈꾸는 23기, 교내 최고 동아리로 들어와!',
    big: false,
    nickname: '밈',
  },
  {
    name: 'DELL',
    time: '목8',
    kind: '퍼포먼스',
    keyword: '밴드',
    sentence: '밴드 동아리로, 함께 곡을 연습하여 무대에 섭니다.',
    big: false,
    nickname: '델',
  },
  {
    name: '매치포인트',
    time: '목8',
    kind: '스포츠',
    keyword: '체육',
    sentence: '스트레스를 풀기 위해 배드민턴을 칩니다.',
    big: false,
    nickname: 'Match Point',
  },
  {
    name: 'GeNiUS',
    time: '목7',
    kind: '과학',
    keyword: '화학',
    sentence: '다양한 화학 관련 실험과 탐구를 진행합니다.',
    big: false,
    nickname: '지니어스',
  },
  {
    name: 'SIN',
    time: '목7',
    kind: '과학',
    keyword: '융합과학',
    sentence:
      '화학과 생명과학을 중심으로 실험 및 탐구를 진행하는 융합과학 동아리입니다.',
    big: false,
    nickname: '사인',
  },
  {
    name: 'INTERPOL',
    time: '목7',
    kind: '사회',
    keyword: '정치 외교 경제 경영',
    sentence:
      '교내 유일의 진짜 문과 동아리, 정치, 외교, 법학, 경제, 경영 등 모든 분야에 대한 탐구와 활동을 진행합니다.',
    big: false,
    nickname: '인터폴',
  },
  {
    name: '글애돝',
    time: '목7',
    kind: '융합',
    keyword: '문예 편집',
    sentence:
      '“우리가 쓰는 글은 항상 빛이 난다”, 빛바랜 추억을 빛나는 글로 담아내는 우리들의 이야기.',
    big: false,
    nickname: '',
  },
  {
    name: 'RCY',
    time: '토4',
    kind: '봉사',
    keyword: '봉사',
    sentence:
      '지원자 수 1위의 교내 최대 규모 봉사동아리로, 입학 설명회나 헌혈 행사를 담당합니다.',
    big: false,
    nickname: '알씨와이',
  },
  {
    name: '라포르',
    time: '목7',
    kind: '융합',
    keyword: '심리학',
    sentence:
      '심리학과 다양한 학문을 융합하여 탐구하고 대규모 심리 실험을 진행하는 인간에 의한, 인간을 위한 동아리입니다.',
    big: false,
    nickname: 'Raport',
  },
  {
    name: 'CUBE',
    time: '목7',
    kind: '과학',
    keyword: '생명과학',
    sentence:
      'One and Only, Only for CUBE. 교내 근본 생명과학 동아리, 오직 CUBE만을 위해 준비된 활동.',
    big: false,
    nickname: '큐브',
  },
  {
    name: '하늘바라기',
    time: '토4',
    kind: '특별활동',
    keyword: '천체 관측',
    sentence:
      '천체 망원경을 이용해 달과 별 등 다양한 천체들을 관측하고, 친목을 도모합니다.',
    big: false,
    nickname: '',
  },
  {
    name: 'HCUtube',
    time: '목8',
    kind: '창작',
    keyword: '영상 제작',
    sentence:
      '가장 인기 있는 플랫폼인 유튜브로 현대청운고에서 일어나는 재미있는 행사와 일들을 영상화하고, 이로써 현대청운고의 홍보 역할을 합니다.',
    big: false,
    nickname: '엣치씨유튜브',
  },
  {
    name: '아리솔',
    time: '목8',
    kind: '특별활동',
    keyword: '도서관 관리',
    sentence:
      '교내 유일 도서관 동아리로써, 도서 서고를 정리하고 대출 및 반납을 담당합니다.',
    big: false,
    nickname: 'Arisol',
  },
  {
    name: '쇼군',
    time: '목8',
    kind: '퍼포먼스',
    keyword: '랩, 힙합',
    sentence: '교내 최고의 힙합 동아리',
    big: false,
    nickname: 'Showgun',
  },
  {
    name: 'SAMDI',
    time: '목7',
    kind: '공학',
    keyword: '공학',
    sentence:
      '프로그래밍, 메타버스 제작뿐만 아니라 당신이 원하는 모든 공학을 할 수 있는 동아리, 삼디입니다.',
    big: false,
    nickname: '삼디',
  },
  {
    name: '동물의 숲',
    time: '목7',
    kind: '과학',
    keyword: '생명과학, 수의학',
    sentence:
      '생명과학, 수의학과 관련된 여러 과학 실험들과 심화 주제 탐구 활동을 합니다.',
    big: false,
    nickname: '',
  },
  {
    name: 'DIXIT',
    time: '토4',
    kind: '특별활동',
    keyword: '언어 및 언어학',
    sentence:
      '여러 언어에 대해 탐구하고 언어 과목 세특 제작에 도움을 주는 광기에 찬 선배들이 기다리는 동아리입니다.',
    big: false,
    nickname: '',
  },
  {
    name: 'BLUECROSS',
    time: '토4',
    kind: '봉사',
    keyword: '의료봉사',
    sentence:
      '의료 관련 포스터 제작 및 캠페인 진행을 통해 교내 봉사와 더불어 의료 지식을 전달하는 동아리입니다.',
    big: false,
    nickname: '블루크로스',
  },
  {
    name: 'COEX',
    time: '토4',
    kind: '특별활동',
    keyword: '환경동물',
    sentence:
      '학교 텃밭 관리 및 자연친화적인 방법을 통해 자연과 공존할 수 있는 방안을 도모합니다.',
    big: false,
    nickname: '코엑스',
  },
  {
    name: '시나브로',
    time: '목7',
    kind: '과학',
    keyword: '생명과학&화학',
    sentence:
      '생명과학과 화학을 탐구하고, 다른 학문과의 연계를 통해 특별한 생기부 제작을 도와드립니다.',
    big: false,
    nickname: 'Sinabro',
  },
  {
    name: 'Palette',
    time: '목8',
    kind: '창작',
    keyword: '미술',
    sentence: '여기는 개성의 색을 전시해둔 미술관, Palette입니다.',
    big: false,
    nickname: '팔레트',
  },
  {
    name: 'AIM',
    time: '목7',
    kind: '과학',
    keyword: '과학, 화학',
    sentence:
      '“Aim for Science, Aim for the Future”, 교내 최고의 화학동아리 AIM입니다.',
    big: false,
    nickname: '에임',
  },
  {
    name: 'it',
    time: '목7',
    kind: '메디컬',
    keyword: '의학',
    sentence: '당신이 원하는 교내 최고의 의학 동아리',
    big: false,
    nickname: '잇',
  },
  {
    name: '강약중강약',
    time: '목7',
    kind: '메디컬',
    keyword: '약학',
    sentence:
      '약학과 관련된 다양한 탐구와 토론 및 토의를 진행하고 다른 분야와 융합하여 심화 탐구를 진행하는 동아리입니다.',
    big: false,
    nickname: '',
  },
  {
    name: '솔매',
    time: '목8',
    kind: '퍼포먼스',
    keyword: '난타',
    sentence: '난타 리듬을 배우고 퍼포먼스를 익히며 무대를 만들어갑니다.',
    big: false,
    nickname: '',
  },
  {
    name: '심포니',
    time: '목8',
    kind: '퍼포먼스',
    keyword: '오케스트라',
    sentence:
      '청운고 유일 관현악 동아리로, 학교 축제와 졸업식 등의 행사에서 공연합니다.',
    big: false,
    nickname: 'sympony',
  },
  {
    name: 'HBS',
    time: '목8',
    kind: '특별활동',
    keyword: '방송부',
    sentence: '현대청운고에 없어서는 안되는 방송부, HBS에서 알려드립니다.',
    big: false,
    nickname: '흐브스',
  },
  {
    name: 'CBP',
    time: '토4',
    kind: '스포츠',
    keyword: '농구',
    sentence: '공부 스트레스는 농구로!',
    big: false,
    nickname: '씨비피시비피',
  },
  {
    name: 'CELLS',
    time: '목7',
    kind: '과학',
    keyword: '융합과학',
    sentence: '물화생지 모든 과학 분야의 탐구와 수준 높은 실험을 진행합니다.',
    big: false,
    nickname: '셀즈',
  },
  {
    name: '랩소디',
    time: '목8',
    kind: '퍼포먼스',
    keyword: '보컬',
    sentence: '보컬 동아리로, 노래를 부르고 공연에 참가합니다.',
    big: false,
    nickname: 'rhapsody',
  },
];
